# Generated by Django 4.2.24 on 2025-10-23 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DRFDosen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('prodi', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DRFPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('upload', models.DateTimeField(auto_now_add=True)),
                ('rating', models.CharField(choices=[('excellent', 1), ('average', 0), ('bad', -1)], default='average', max_length=10)),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='image/')),
            ],
            options={
                'ordering': ['upload'],
            },
        ),
        migrations.CreateModel(
            name='DRFStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('nim', models.CharField(max_length=20)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='basic_api.drfdosen')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
