# Generated by Django 4.2.24 on 2025-10-03 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mahasiswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('nim', models.CharField(max_length=20)),
                ('jurusan', models.CharField(max_length=50)),
                ('angkatan', models.IntegerField()),
                ('jenis_kelamin', models.CharField(max_length=10)),
                ('email_outlook', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('no_hp', models.CharField(max_length=15)),
                ('bukti_konsultasi', models.FileField(upload_to='bukti_konsultasi/')),
                ('sptjm', models.FileField(upload_to='sptjm/')),
                ('protofolio', models.FileField(upload_to='protofolio/')),
                ('cv', models.FileField(upload_to='cv/')),
            ],
        ),
        migrations.CreateModel(
            name='Lowongan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periode_magang', models.CharField(max_length=50)),
                ('posisi', models.CharField(max_length=100)),
                ('nama_perusahaan', models.CharField(max_length=100)),
                ('alamat_perusahaan', models.CharField(max_length=200)),
                ('bidang_usaha_perusahaan', models.CharField(max_length=100)),
                ('nama_supervisor', models.CharField(max_length=100)),
                ('email_supervisor', models.EmailField(max_length=254)),
                ('kontak_wa_supervisor', models.CharField(max_length=15)),
                ('bukti_konfirmasi', models.FileField(upload_to='bukti_konfirmasi/')),
                ('mahasiswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lowongans', to='CoopWeb.mahasiswa')),
            ],
        ),
    ]
