# Generated by Django 4.2.24 on 2025-10-03 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CoopWeb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaporanKemajuan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('profil_perusahaan', models.TextField()),
                ('jobdesk', models.TextField()),
                ('suasana_lingkungan_pekerjaan', models.TextField()),
                ('apa_yang_didapatkan_dari_perkuliahan', models.TextField()),
                ('apa_yang_belum_didapatkan_dalam_pembelajaran', models.TextField()),
                ('mahasiswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laporan_kemajuans', to='CoopWeb.mahasiswa')),
            ],
        ),
    ]
