# Generated by Django 4.2.24 on 2025-10-03 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CoopWeb', '0002_laporankemajuan'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaporanAkhir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pengalaman_magang', models.TextField()),
                ('laporan_hasil_magang', models.FileField(upload_to='laporan_hasil_magang/')),
                ('mahasiswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laporan_akhirs', to='CoopWeb.mahasiswa')),
            ],
        ),
    ]
