# Generated by Django 4.2.24 on 2025-10-03 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CoopWeb', '0003_laporanakhir'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelesaiCoop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_mahasiswa', models.CharField(max_length=100)),
                ('nim', models.CharField(max_length=20)),
                ('program_studi', models.CharField(max_length=50)),
                ('nama_perusahaan', models.CharField(max_length=100)),
                ('periode_magang', models.CharField(max_length=50)),
                ('konversi_nilai_coop', models.CharField(max_length=50)),
                ('mahasiswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selesai_coops', to='CoopWeb.mahasiswa')),
            ],
        ),
    ]
